# Generated by Django 6.0.3 on 2026-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay1', models.CharField(max_length=10)),
                ('relay2', models.CharField(max_length=10)),
                ('relay3', models.CharField(max_length=10)),
                ('relay4', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mqtt', 'MQTT')], max_length=10)),
                ('topic', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay1', models.CharField(default='off', max_length=10)),
                ('relay2', models.CharField(default='off', max_length=10)),
                ('relay3', models.CharField(default='off', max_length=10)),
                ('relay4', models.CharField(default='off', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
